name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backendimage .
          docker push ${{ secrets.DOCKER_USERNAME }}/backendimage

      - name: Build and push frontend image
        working-directory: ../frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend
